/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package secondproject;
import com.Calculator;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	Calculator c=new Calculator();
	System.out.println(c.add(3,5));
    }
}
